# Generated by Django 5.2.4 on 2025-07-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
