# Generated by Django 5.2.4 on 2025-07-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamspace", "0002_worker_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ["position_priority", "last_name"]},
        ),
        migrations.AddField(
            model_name="worker",
            name="position_priority",
            field=models.PositiveSmallIntegerField(default=99),
        ),
    ]
