# Generated by Django 5.2.4 on 2025-07-10 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamspace", "0003_alter_worker_options_worker_position_priority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="teems",
            new_name="teams",
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("document", models.FileField(upload_to="documents/")),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="doc_hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teamspace.document",
            ),
        ),
    ]
