# Generated by Django 5.2.4 on 2025-07-11 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamspace", "0005_task_created_by_task_project_alter_task_assignees"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "priority"]},
        ),
        migrations.RemoveField(
            model_name="project",
            name="doc_hub",
        ),
        migrations.AddField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="teamspace.project",
            ),
        ),
    ]
