# Generated by Django 5.2.4 on 2025-07-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teamspace", "0006_alter_task_options_remove_project_doc_hub_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed"]},
        ),
    ]
