# Generated by Django 5.2.4 on 2026-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamspace", "0008_alter_worker_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Вік"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="github_url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="GitHub"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="linkedin_url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="LinkedIn"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("manager", "Manager"), ("user", "User")],
                default="user",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="skype",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Skype"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="telegram",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Telegram"
            ),
        ),
    ]
