# Generated by Django 5.2.4 on 2026-06-08 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamspace", "0009_worker_age_worker_github_url_worker_linkedin_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_retention_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="How many days to keep logs"
                    ),
                ),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.AlterField(
            model_name="worker",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Age"
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("manager", "Manager"), ("user", "User")],
                default="user",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Action Log",
                "verbose_name_plural": "User Action Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
